#!/bin/bash

for var in $(<dnsServers.txt)
do
     echo "Accessing $var"
     tmux new-window -n:"$var" ssh -l ubc_cpen431_4 -i ~/.ssh/id_rsa "$var" "java -jar -Xmx64m A4-1.0.jar spawn -name localhost -port 11111 -nodes ipServers.txt"
     #tmux new-window -n:"$var" ssh -l ubc_cpen431_4 -i ~/.ssh/id_rsa "$var" "java -jar -Xmx64m CPEN431-1.0.jar spawn -name test -port 10696"
 done
